




























export default Header;};  );    </AppBar>      </Toolbar>        </Box>          ))}            </Button>              {link.label}            <Button key={index} color="inherit" component={Link} href={link.url}>          {navLinks.map((link, index) => (        <Box>        </Typography>          {title}        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>      <Toolbar>    <AppBar position="static">  return (const Header: React.FC<HeaderProps> = ({ title, navLinks }) => {}  navLinks: { label: string; url: string }[];  title: string;interface HeaderProps {import Link from 'next/link';import { AppBar, Toolbar, Typography, Button, Box } from '@mui/material';import React from 'react';